version: '3.8'

services:
  app:
    image: node:14
    container_name: task_management_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:4.4
    container_name: task_management_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    container_name: task_management_redis
    ports:
      - 6379:6379

volumes:
  mongo-data:
